[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn -w 2 -b 0.0.0.0:$PORT enhanced_payment_api:app"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"