[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python payment_api.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { PYTHON_VERSION = "3.11.7" }
